language: go

sudo: false

addons:
  postgresql: "9.4"

matrix:
  fast_finish: true
  include:
    - go: 1.4
      env: TEST_BACKEND=on
    - go: 1.5
      env: TEST_BACKEND=on
    - go: 1.6
      env: TEST_BACKEND=on
    - go: 1.6
      env: TEST_FRONTEND=on TRAVIS_NODE_VERSION="0.12"
    - go: 1.6
      env: TEST_BUILD=on    TRAVIS_NODE_VERSION="0.12"

before_script:
  - curl https://s3.amazonaws.com/influxdb/influxdb-0.12.0-1_linux_amd64.tar.gz | tar xvzf -
  - ./usr/bin/influxd &
  - sleep 2
  - if [ "$TEST_BACKEND" = "on" ]; then psql -c 'create database travis_ci_test;' -U postgres; fi;
  - if [ "$TEST_BACKEND" = "on" ]; then cp -f test/config_travis.toml test/config_test.toml; fi;

install:
  # from http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
  - if [ "$TRAVIS_NODE_VERSION" != "" ]; then rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION; fi;
  - if [ "$TEST_FRONTEND" = "on" ]; then make install-frontend; fi
  - if [ "$TEST_BACKEND" = "on" ];  then make install-backend; fi
  - if [ "$TEST_BUILD" = "on" ];    then make install; fi;

script:
  - if [ "$TEST_BACKEND" = "on" ];  then make test-backend; fi
  - if [ "$TEST_FRONTEND" = "on" ]; then make test-frontend; fi
  - if [ "$TEST_BUILD" = "on" ];    then make build; fi;
